replicaCount: 1
image:
  repository: 
  tag: test
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 5000
ingress:
  enabled: false
  annotations: []
  hosts: []
  tls: []

env:
  - name: MONGO_URI
    value: "mongodb://mongodb-cluster.mongodb-cluster.svc.cluster.local:27017/" 

envFrom:
  configMaps:
    - name: app
  secrets: []
nodeSelector: {}
tolerations: []
affinity: {}

    
resources:
  limits:
    cpu: 1500m  # Set appropriate CPU limits
    memory: 2048Mi  # Set appropriate memory limits
  requests:
    cpu: 1000m  # Set CPU requests
    memory: 1024Mi  # Set memory requests    
  
startupProbe:
  enabled: true
  httpGet:
    path: /ping  # Assuming /ping is the health check endpoint
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 40
  periodSeconds: 10

livenessProbe:
  enabled: true
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 40
  periodSeconds: 10
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - name: cpu
      targetUtilization: 55
  scaleUp:
    stabilizationWindowSeconds: 15
    policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      - type: Percent
        value: 20
        periodSeconds: 30
    selectPolicy: Max
  scaleDown:
    stabilizationWindowSeconds: 30
    policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      - type: Percent
        value: 20
        periodSeconds: 30
    selectPolicy: Min
