daemonset:
  # Annotations to apply to the daemonset
  annotations: {}
  # Additional labels
  labels: {}
  affinity: {}
  # Include the daemonset
  enabled: true
  # Extra environment variables for Filebeat container.
  envFrom: []
  # Removed or cleared extraEnvs
  extraEnvs: []
  # Allows you to add any config files in /usr/share/filebeat
  extraVolumes: []
  extraVolumeMounts: []
  hostNetworking: false
  # Updated filebeat.yml without SSL and authentication
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
        - type: container
          paths:
            - /var/log/containers/*.log
          processors:
            - add_kubernetes_metadata:
                host: ${NODE_NAME}
                matchers:
                  - logs_path:
                      logs_path: "/var/log/containers/"

      output.elasticsearch:
        hosts: ["http://elasticsearch.logging.svc.cluster.local:9200"]
        ssl:
          enabled: false

      setup.kibana:
        host: "http://elasticsearch-kibana.logging.svc.cluster.local:5601"
        ssl.enabled: false
  # Removed or cleared secretMounts
  secretMounts: []
  # Various pod security context settings.
  securityContext:
    runAsUser: 0
    privileged: false
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "200Mi"
  tolerations: []

deployment:
  # Annotations to apply to the deployment
  annotations: {}
  # Additional labels
  labels: {}
  affinity: {}
  # Include the deployment
  enabled: false
  # Extra environment variables for Filebeat container.
  envFrom: []
  # Removed or cleared extraEnvs
  extraEnvs: []
  # Allows you to add any config files in /usr/share/filebeat
  extraVolumes: []
  extraVolumeMounts: []
  # Updated filebeat.yml without SSL and authentication
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
        - type: log
          paths:
            - /usr/share/filebeat/logs/filebeat

      output.elasticsearch:
        hosts: ["http://elasticsearch.logging.svc.cluster.local:9200"]
        ssl:
          enabled: false

      setup.kibana:
        host: "http://elasticsearch-kibana.logging.svc.cluster.local:5601"
        ssl.enabled: false
  # Removed or cleared secretMounts
  secretMounts: []
  # Various pod security context settings.
  securityContext:
    runAsUser: 0
    privileged: false
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "1000m"
      memory: "200Mi"
  tolerations: []

# Replicas being used for the filebeat deployment
replicas: 1

extraContainers: ""
extraInitContainers: []

# Root directory where Filebeat will write data to in order to persist registry data across pod restarts (file position and other metadata).
hostPathRoot: /var/lib

dnsConfig: {}
hostAliases: []
image: "docker.elastic.co/beats/filebeat"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"
imagePullSecrets: []

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        curl --fail 127.0.0.1:5066
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5

readinessProbe:
  exec:
    command:
      - sh
      - -c
      - |
        #!/usr/bin/env bash -e
        filebeat test output
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5

# Whether this chart should self-manage its service account, role, and associated role binding.
managedServiceAccount: true

clusterRoleRules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch

podAnnotations: {}

# Custom service account override that the pod will use
serviceAccount: ""
# Removed or commented out if using Option 1
# serviceAccount:
#   create: false
#   name: default

# Annotations to add to the ServiceAccount that is created if the serviceAccount value isn't set.
serviceAccountAnnotations: {}
# eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/k8s.clustername.namespace.serviceaccount

# How long to wait for Filebeat pods to stop gracefully
terminationGracePeriod: 30
# PriorityClass settings
priorityClassName: ""

updateStrategy: RollingUpdate

# Override various naming aspects of this chart
nameOverride: ""
fullnameOverride: ""
